### PR TITLE
Add deck to libraries table

### PR DESCRIPTION
**Pull request by SrGaabriel**
Repository: https://github.com/SrGaabriel/deck

### CODE REVIEW

**Comment by shayypy** [comment]
Does this library back-off 429s/use the `retry-after` header or does it simply let the request fail? I looked around the request code and couldn't find anything about it.

**Comment by SrGaabriel** [comment]
Sorry for the late reply, but last time I tried parsing 429s the `retry-after` header wasn't present, but I'll check once again.

**Comment by SrGaabriel** [comment]
Yes, I keep getting ratelimited but none of the responses have the `retry-after` header.
image

**Comment by shayypy** [comment]
It is there sometimes, I've observed it while you're getting rate-limited by slowmode. If it isn't there you should backoff arbitrarily or just let the request fail

**Comment by SrGaabriel** [comment]
> It is there sometimes, I've observed it while you're getting rate-limited by slowmode. If it isn't there you should backoff arbitrarily or just let the request fail

Okay, I'll do just that.

**Comment by SrGaabriel** [comment]
Done: https://github.com/SrGaabriel/deck/commit/0fd70cdc271401f31b8c9831bd65bc24d6696e3f

**Pull request merged**
