### PR TITLE
Added `Guilded.TS` to libraries

### PR DESCRIPTION
**Pull request by DanieliusDev**
Added `Guilded.TS` to libraries.
Guilded.TS supports the official bot API.

### CODE REVIEW

**Review by shayypy — CHANGES_REQUESTED** [review]
Please alphabetize your entry.

**Comment by gamertike** [comment]
@shayypy should i keep my lib near the js/ts libs?

**Comment by shayypy** [comment]
The entire list should be sorted alphabetically; don't group it independently.

**Comment by gamertike** [comment]
> The entire list should be sorted alphabetically; don't group it independently.

Alr.

**Comment by shayypy** [comment]
You should prefer the `retry-after` header when it is present. I don't see this in `RestManager.ts`.

**Comment by gamertike** [comment]
@shayypy im ready for my my lib to be reviewed or whatever.

**Comment by gamertike** [comment]
> You should prefer the `retry-after` header when it is present. I don't see this in `RestManager.ts`.

ok, ill probably implement this tomorrow then.

**Comment by gamertike** [comment]
Hi @shayypy , ik its been a long time since i said i would add the `Retry-After` header. Well the reason it took a week is because i was working on a big update. The update is now released with the feature you requested.
https://github.com/guildedts/guilded.ts/blob/main/packages/rest/src/RestManager.ts#L70
I hope this is enough for you to add my library to the list :)

**Pull request closed without merging**
